"""Render the archived public updates as crawlable HTML. Never edit source records."""
from pathlib import Path
from html import escape
import json

root = Path(__file__).resolve().parents[1]
updates = json.loads((root / 'assets/updates.json').read_text(encoding='utf-8'))
entries = []
for item in updates:
    date = escape(item.get('date', ''))
    title = escape(item.get('title', 'Untitled update'))
    text = escape(item.get('text', '')).replace('\n', '<br>')
    entries.append(f'<article class="archive-entry"><time datetime="{date}">{date}</time><div><h2>{title}</h2><p>{text}</p></div></article>')
html = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080d12"><title>Build History | Alpha Husky</title><meta name="description" content="Dated Alpha Husky development updates and archived project material. The original records are preserved as published."><link rel="canonical" href="https://alphahusky.win/history.html"><link rel="icon" href="/logo.png" type="image/jpeg"><link rel="stylesheet" href="/css/site.css"><script src="/js/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="shell header-inner"><a class="brand" href="/"><img src="/logo.png" width="42" height="42" alt=""><span>ALPHA <b>HUSKY</b></span></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-controls="site-nav" aria-expanded="false"><span></span><span></span><span></span></button><nav class="site-nav" id="site-nav" aria-label="Main navigation"><a href="/#game">The game</a><a href="/#world">The world</a><a href="/history.html" aria-current="page">Build history</a><a href="/#howl">HOWL</a><a href="/#verify">Verify</a><a class="button button-small" href="https://t.me/Alpha_husky_bot/AlphaHuskyHub" target="_blank" rel="noopener noreferrer">Play Alpha Husky ↗</a></nav></div></header><main id="main" class="archive-main shell"><p class="eyebrow">The record / preserved</p><h1>Built in public.</h1><p class="archive-intro">These dated notes preserve what the project reported at the time. Early plans, timelines and feature states are historical records, not current product promises. For today's game, start on the <a class="text-link" href="/">homepage ↗</a>.</p><section id="archive" aria-labelledby="archive-title"><h2 id="archive-title">Development notes</h2><div class="archive-list">''' + '\n'.join(entries) + '''</div></section><section aria-labelledby="more-title"><h2 id="more-title">Further into the archive</h2><div class="archive-more"><a href="/archive/legacy-home.html">Earlier website snapshot ↗</a><a href="/assets/updates.json">Original update data ↗</a><a href="/howloween.html">HOWL-o-ween event ↗</a><a href="/eclipse-event.html">Eclipse event ↗</a></div></section></main><footer class="site-footer"><div class="shell footer-inner"><a class="brand" href="/"><img src="/logo.png" width="38" height="38" alt=""><span>ALPHA <b>HUSKY</b></span></a><nav aria-label="Footer navigation"><a href="/">Home</a><a href="/contact.html">Contact</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="/cookies.html">Cookies</a></nav><p>Game first. History recorded honestly.</p></div></footer></body></html>'''
(root / 'history.html').write_text(html, encoding='utf-8')
